import anthropic
import json
import re
from pathlib import Path
from pipeline.silver_to_gold import (
    VALID_PAGE_TYPES,
    build_wiki_page,
    write_wiki_page,
    load_existing_body,
    append_to_wiki_page,
    verify_existing_body_unchanged,
)

# Types that Pass 2 chunk extraction must NEVER create.
# "strategy" is allowed (with slug-whitelist guard in validate_page_spec).
# "overview" is created by holistic_synthesizer.py (Pass 1), not here.
PASS3_FORBIDDEN_TYPES = frozenset({
    "overview",   # created by holistic_synthesizer.py (Pass 1) — never by chunked extraction
    "topic",      # human-declared only; LLM never creates topic pages
    "mechanism",  # requires cross-source corroboration; not created per-chunk
    "synthesis",  # generated by post-ingest pipeline, not during extraction
})


WIKI_PAGES_SYSTEM = """You are a wiki page generator for the A2Zero climate wiki.
You receive one section of an A2Zero source document and generate wiki page specs
for entities mentioned in the section.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEVER CREATE these page types:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- type: overview  — created by holistic_synthesizer.py (Pass 1) before chunking. Never create.
- type: topic     — declared manually by the research team. Never create.
- type: mechanism — requires evidence from ≥2 independent sources. Never create per-chunk.
- type: synthesis — generated by post-ingest pipeline. Never create during extraction.
- type: commitment — this type is eliminated. Use "initiative" for all CAP actions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WIKILINK FORMAT — mandatory everywhere:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All entity references MUST use Obsidian wikilink format.
The "Source path" in the user message gives the vault-relative path for citations.

  Single frontmatter value:    "[[actors/osi]]"
  Frontmatter list item:       "[[actors/osi]]"  ← each list item is a quoted wikilink string
  Body first mention:          [[actors/osi|Office of Sustainability and Innovations]]
  Body later mentions:         [[actors/osi|OSI]]
  Source citation (REQUIRED):  ([[sources/cap/cap-2020|cap-2020]])

CITATIONS: Every factual sentence in "body" must end with a source citation in this exact format:
  ([[{source_path}|{source_uuid}]])
where {source_path} = the Silver path value from the user message, and {source_uuid} = the Source UUID value.
Exceptions: transitional sentences, section headers, cross-references to other wiki pages.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
A2ZERO HIERARCHY — use to assign parent-strategy:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[[strategies/strategy-1-renewable-grid]] — 100% Renewable Energy Grid
  Includes: CCA, Landfill Solar, Community Solar, Onsite Renewables Bulk Buy

[[strategies/strategy-2-electrification]] — Building Electrification
  Includes: heat pump programs, appliance electrification, EV fleet, building fuel switching

[[strategies/strategy-3-building-efficiency]] — Building Energy Efficiency
  Includes: weatherization, energy audits, efficiency retrofits, building standards

[[strategies/strategy-4-vmt-reduction]] — Vehicle Miles Traveled Reduction
  Includes: transit expansion, non-motorized transport, parking reform, mixed-use development

[[strategies/strategy-5-materials-waste]] — Materials & Waste
  Includes: zero waste plan, composting, recycling expansion, circular economy, food waste

[[strategies/strategy-6-resilience]] — Community Resilience
  Includes: Resilience Hubs, emergency preparedness, environmental monitoring, tree canopy

[[strategies/strategy-7-engagement]] — Community Engagement & Equity
  Includes: Equity Program, Sustaining Ann Arbor Together grants, Carbon Offsets, Internal Carbon Price

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
UNIVERSAL RULES:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Extract ONLY what the text explicitly states — never invent details
- Slugify names: lowercase, hyphens for spaces, drop special chars
  "Office of Sustainability and Innovations" → "office-of-sustainability-and-innovations"
  Use acronym when it IS the canonical name: "OSI" → "osi", "DTE Energy" → "dte-energy"
- One page spec per entity — do not create the same entity twice in one response
- Return [] if no qualifying entities are found in this section

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE TYPES TO CREATE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. STRATEGY — one of the 7 pre-existing A2Zero strategy pages. Append context only.
   ONLY create a strategy spec if this section explicitly describes a strategy's goal or actions.
   The slug MUST exactly match one of the 7 slugs listed above — no other strategy slugs exist.
   Slug: "strategies/{exact-pre-existing-slug}"
   Frontmatter:
     type: strategy
     title: (exact strategy title from source)
     strategy-number: (integer 1-7)
     parent-plan: "[[plans/cap-2020]]"
     goal: (1-sentence goal statement for this strategy, from source)
     initiatives: ["[[initiatives/slug1]]", "[[initiatives/slug2]]"]
     source-first-seen: "[[{source_path}]]"
     tags: [3-5 keywords]
     last-updated: (today's date YYYY-MM-DD)

2. INITIATIVE — a named, bounded program or project. THIS REPLACES "commitment".
   Every numbered CAP Action (### heading) MUST become an initiative page.
   Every annual report "Next Steps" item becomes an initiative page.
   Do NOT create for passing mentions or unnamed policy considerations.
   Slug: "initiatives/{kebab-program-name}"
   Frontmatter:
     type: initiative
     title: (program name)
     parent-strategy: "[[strategies/{slug}]]"
     related-strategies: ["[[strategies/{slug}]]"]
     party-responsible: "[[actors/{slug}]]"
     partners: ["[[actors/{slug}]]"]
     status: (planned | committed | active | complete | abandoned | unknown)
     launched: (year as integer, or null)
     locations: ["[[locations/{slug}]]"]
     funding-events: ["[[funding-events/{slug}]]"]
     milestones:
       - year: (integer)
         target: (string describing the milestone — extract from timelines or Next Steps)
         status: unverified
         source: "[[{source_path}]]"
     source-first-seen: "[[{source_path}]]"
     tags: [3-6 keywords]
     last-updated: (today's date YYYY-MM-DD)

3. ACTOR — a person or organization with a named role in A2Zero.
   Create only when a clear role is described. Do NOT create for passing mentions.
   Slug: "actors/{kebab-name}"
   Frontmatter:
     type: actor
     title: (full name)
     actor-type: (person | government-office | nonprofit | utility | university | funder | company)
     role: (their role in A2Zero, one phrase)
     affiliation: "[[actors/{parent-org-slug}]]"
     elected: (true | false | null)
     active-years: [list of integer years, or []]
     programs-involved: ["[[initiatives/{slug}]]"]
     tags: [3-5 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)

4. FUNDING-EVENT — a specific dollar allocation with named source AND recipient.
   Create only when both amount AND funding source are explicitly stated.
   Slug: "funding-events/{kebab-fund-name-year}"
   Frontmatter:
     type: funding-event
     title: (fund name including org and year)
     date: (YYYY or YYYY-MM)
     amount: (integer in dollars)
     currency: USD
     fund-type: (federal-grant | state-grant | local-millage | philanthropic-grant | utility-program | federal-incentive | budget-allocation)
     funder: "[[actors/{slug}]]"
     recipient: "[[actors/{slug}]]"
     funds-initiatives: ["[[initiatives/{slug}]]"]
     status: (announced | awarded | disbursed | completed | terminated | on-hold)
     transferable: (true | false)
     tags: [3-5 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)

5. TECHNOLOGY — a technology type Ann Arbor is deploying in A2Zero programs.
   Create when barriers, costs, or deployment details are documented — not for passing mentions.
   Create only for actual technical systems (solar PV, heat pumps, battery storage, EVs).
   Do NOT create for policy mechanisms like Community Choice Aggregation — that is an initiative.
   Slug: "technology/{kebab-tech-common-name}"
   Frontmatter:
     type: technology
     title: (full technology name)
     common-name: (short common name, e.g. "geothermal" | "heat-pump" | "solar-pv")
     tech-type: (heating-cooling | solar | storage | efficiency | grid | ev | building-envelope | other)
     a2zero-context: (1-sentence describing how Ann Arbor uses this technology)
     initiatives: ["[[initiatives/{slug}]]"]
     locations: ["[[locations/{slug}]]"]
     deployment-status: (planned | in-progress | operational | completed | abandoned)
     cost-context: (string summarizing known costs, or null)
     barriers-encountered: [list of barrier keyword strings, or []]
     transferability: (high | medium | low)
     tags: [3-6 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)

6. LOCATION — a specific named site of A2Zero program activity.
   Create when a location is named as a site of initiative activity, not just mentioned in passing.
   Slug: "locations/{kebab-location-name}"
   Frontmatter:
     type: location
     title: (full location name)
     location-type: (county | city | neighborhood | park | facility | infrastructure | district | school)
     parent-location: "[[locations/{slug}]]"
     owned-by: (city | county | nonprofit | university | school-district | private | null)
     initiatives: ["[[initiatives/{slug}]]"]
     tags: [3-5 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)

7. CONTRADICTION — conflicting claims about the same fact, broadly interpreted.
   Create when numbers, dates, status claims, targets, costs, or actor roles conflict within or
   across sources. Do NOT silently resolve conflicts — surface them here for human review.
   Slug: "contradictions/{kebab-brief-description}"
   Frontmatter:
     type: contradiction
     title: (brief description of the conflict)
     sources: ["[[{source_path}]]"]
     cross-source: (true if conflict spans different source documents; false if within same source)
     status: unresolved
     related-initiatives: ["[[initiatives/{slug}]]"]
     tags: [3-5 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)
   Body: document both conflicting claims side by side, each ending with a citation.

8. MEETING — a deliberative body meeting where A2Zero items were discussed.
   Distinguish from POLITICAL-EVENT: MEETING = where debate happened; POLITICAL-EVENT = the outcome.
   For significant votes, create BOTH a meeting page AND a political-event page.
   Slug: "meetings/YYYY-MM-DD-{body-slug}"
   Frontmatter:
     type: meeting
     title: "{Body} — {YYYY-MM-DD} ({brief A2Zero topic})"
     date: (YYYY-MM-DD)
     body: (city-council | sustainability-commission | planning-commission | other)
     source-uuid: (source UUID string — not a wikilink)
     agenda-items: ["[[initiatives/{slug}]]"]
     decisions: [list of decision strings, or []]
     actors: ["[[actors/{slug}]]"]
     tags: [3-5 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)

9. FRAMING — how an A2Zero issue is deliberately talked about by stakeholders.
   Create only for named framing strategies with documented strategic intent — not every
   communications mention. The framing must be deliberate and politically significant.
   Slug: "framing/{kebab-framing-title}"
   Frontmatter:
     type: framing
     title: (descriptive framing title)
     initiative: "[[initiatives/{slug}]]"
     period: (YYYY-YYYY or YYYY)
     actors: ["[[actors/{slug}]]"]
     audiences: [list of audience strings]
     evolution: (true | false)
     tags: [3-5 keywords]
     source-first-seen: "[[{source_path}]]"
     last-updated: (today's date YYYY-MM-DD)

10. POLITICAL-EVENT — a discrete political outcome with lasting legal or political effect.
    Create for council resolutions, referendums, elections, key appointments.
    Slug: "political-events/YYYY-MM-DD-{slug}"
    Frontmatter:
      type: political-event
      title: (descriptive title including body and outcome)
      date: (YYYY-MM-DD)
      event-type: (referendum | council-resolution | election | appointment | legal-ruling | regulatory-decision)
      outcome: (passed | failed | approved | rejected | appointed | other)
      margin: (vote margin string, or null)
      legal-effect: (1-sentence description of what this authorizes or prohibits, or null)
      programs-authorized: ["[[initiatives/{slug}]]"]
      actors: ["[[actors/{slug}]]"]
      tags: [3-5 keywords]
      source-first-seen: "[[{source_path}]]"
      last-updated: (today's date YYYY-MM-DD)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT SCHEMA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Every element of the returned JSON array must have exactly these four keys:
{
  "page_type": "<one of the 10 types above>",
  "slug": "<category/kebab-name>",
  "frontmatter": { <required fields per type; all entity refs as "[[wikilinks]]"> },
  "body": "<2-4 factual sentences; every factual sentence ends with ([[sources/path|uuid]])>"
}
Return ONLY the JSON array. No prose, no markdown fence, no explanation."""


def parse_llm_pages_response(raw: str) -> list[dict]:
    cleaned = re.sub(r"^```(?:json)?\n?", "", raw.strip())
    cleaned = re.sub(r"\n?```$", "", cleaned)
    data = json.loads(cleaned)
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON array, got {type(data).__name__}")
    return data


def validate_page_spec(
    spec: dict,
    allowed_strategy_slugs: frozenset[str] | None = None,
) -> list[str]:
    errors = []
    for field in ("page_type", "slug", "frontmatter", "body"):
        if field not in spec:
            errors.append(f"missing required field: {field}")
    if "body" in spec and not spec.get("body"):
        errors.append("body must not be empty")
    if "page_type" in spec:
        pt = spec["page_type"]
        if pt not in VALID_PAGE_TYPES:
            errors.append(
                f"invalid page_type: {pt!r} — must be one of {sorted(VALID_PAGE_TYPES)}"
            )
        elif pt in PASS3_FORBIDDEN_TYPES:
            errors.append(
                f"page_type {pt!r} is forbidden in Pass 3 — "
                f"these pages are created by a separate process"
            )
        elif pt == "strategy" and allowed_strategy_slugs is not None:
            slug = spec.get("slug", "")
            if slug not in allowed_strategy_slugs:
                errors.append(
                    f"strategy slug {slug!r} is not a pre-existing strategy stub — "
                    f"only these slugs are allowed: {sorted(allowed_strategy_slugs)}"
                )
    return errors


def write_or_append_page(spec: dict, wiki_root: str, source_uuid: str):
    slug = spec["slug"]
    page_path = Path(wiki_root) / (slug + ".md")

    if page_path.exists():
        existing_body = load_existing_body(str(page_path))
        new_section = f"\n<!-- source: {source_uuid} -->\n{spec['body']}\n"
        append_to_wiki_page(str(page_path), new_section, source_uuid)
        verify_existing_body_unchanged(str(page_path), existing_body)
    else:
        page = build_wiki_page(
            page_type=spec["page_type"],
            slug=slug,
            frontmatter=spec["frontmatter"],
            body=spec["body"],
        )
        write_wiki_page(page, wiki_root, exist_ok=False)


def extract_wiki_pages_from_chunk(
    chunk_text: str,
    source_uuid: str,
    source_rel_path: str,
    context_header: str,
    source_type: str,
    wiki_root: str,
    run_date: str,
) -> list[dict]:
    try:
        client = anthropic.Anthropic()
        prompt = (
            f"{context_header}\n\n"
            f"[SECTION CONTENT]\n{chunk_text}\n[END SECTION]\n\n"
            f"Source UUID: {source_uuid}\n"
            f"Source path: {source_rel_path}\n"
            f"Source type: {source_type}\n"
            f"Today's date: {run_date}"
        )
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=16384,
            temperature=0.2,
            system=WIKI_PAGES_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        if response.stop_reason == "max_tokens":
            print("[wiki_writer] WARNING: response truncated (max_tokens hit). Chunk skipped.")
            return []
        raw = response.content[0].text
        specs = parse_llm_pages_response(raw)
    except Exception as e:
        print(f"[wiki_writer] WARNING: page extraction failed for chunk: {e}")
        return []

    # Build allowed strategy slugs from wiki_root/strategies/ for whitelist guard.
    strategy_dir = Path(wiki_root) / "strategies"
    allowed_strategy_slugs: frozenset[str] = frozenset(
        f"strategies/{p.stem}" for p in strategy_dir.glob("*.md")
    ) if strategy_dir.exists() else frozenset()

    written = []
    for spec in specs:
        errors = validate_page_spec(spec, allowed_strategy_slugs=allowed_strategy_slugs)
        if errors:
            print(
                f"[wiki_writer] WARNING: invalid page spec skipped: {errors} "
                f"— {spec.get('slug', '?')}"
            )
            continue
        try:
            write_or_append_page(spec, wiki_root=wiki_root, source_uuid=source_uuid)
            written.append(spec)
        except Exception as e:
            print(f"[wiki_writer] WARNING: failed to write page {spec.get('slug', '?')}: {e}")

    return written
