import anthropic
import json
import re
from pathlib import Path
from pipeline.silver_to_gold import (
    VALID_PAGE_TYPES,
    build_wiki_page,
    write_wiki_page,
    load_existing_body,
    append_to_wiki_page,
    verify_existing_body_unchanged,
)

# Types that Pass 3 chunk extraction must NEVER create.
# "strategy" is allowed (with slug-whitelist guard in validate_page_spec).
# "plan" is created by plan_extractor.py before chunking, not here.
PASS3_FORBIDDEN_TYPES = frozenset({
    "plan",       # created by dedicated first-pass call before chunking
    "topic",      # human-declared only; LLM never creates topic pages
    "mechanism",  # requires cross-source corroboration; not created per-chunk
    "synthesis",  # generated by post-ingest pipeline, not during extraction
})


WIKI_PAGES_SYSTEM = """You are a wiki page generator for the A2Zero climate wiki.
You receive one section of an A2Zero source document and generate wiki page specs
for entities mentioned in the section.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEVER CREATE these page types:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- type: strategy  — the 7 A2Zero strategy pages are pre-created. If a section
  discusses work under a strategy, create commitment or initiative pages. Never
  create or overwrite a strategy page.
- type: topic  — topic pages are declared manually by the research team. Never
  create one. If content seems to warrant a new topic, note it in an initiative
  body but do not create the page.
- type: mechanism  — mechanism pages require evidence from at least 2 independent
  sources. Never create one from a single source chunk.
- type: synthesis  — generated by the post-ingest pipeline, never during extraction.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
UNIVERSAL RULES (apply to all types):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- Extract ONLY what the text explicitly states — never invent details
- CITATIONS REQUIRED: every factual sentence in "body" must end with
  (source: SOURCE_UUID) referencing the document where that fact appears.
  Example: "The city committed to 100% renewable electricity by 2030. (source: cap-2020)"
  Exceptions: transitional sentences, section headers, cross-references to other wiki pages.
- Slugify names: lowercase, hyphens for spaces, drop special chars.
  "Office of Sustainability and Innovations" → "office-of-sustainability-and-innovations"
  Exception: use the acronym when it IS the canonical name:
  "OSI" → "osi", "DTE Energy" → "dte"
- One page spec per entity — do not duplicate the same entity in one response
- Return [] if no qualifying entities are found in this section

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE TYPES TO CREATE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. COMMITMENT — a specific promise, plan, or action the city commits to.
   Every numbered CAP Action (### heading) MUST become a commitment page.
   Annual report "Next Steps" items each become a commitment page.
   Slug: "commitments/{kebab-action-title}"
   Frontmatter:
     type: commitment
     title: (exact action title from source)
     made-in: (source UUID)
     made-in-section: "CAP Actions"  # or "Next Steps" | "council-debate" | "press-release"
     target-year: (e.g. "year1" | "year2" | "unspecified")
     status: unverified  # always "unverified" for CAP actions; annual reports may show evidence
     confidence: high    # "high" for named CAP actions/Next Steps; "medium" for press release; "low" for informal
     fulfilled-in: null
     fulfilled-evidence: null
     tags: [3-6 relevant keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

2. INITIATIVE — a named, bounded program or project the city is implementing.
   Create when a named program is mentioned with enough specificity to track over time.
   Do NOT create for one-off events, unnamed policy considerations, or single mentions.
   Slug: "initiatives/{kebab-program-name}"
   Frontmatter:
     type: initiative
     title: (program name)
     launched: (year as integer, or null if unknown)
     status: (active | committed | completed | stalled | on-hold | unknown)
     parent-strategy: (single primary strategy slug, e.g. "strategy-1")
     related-strategies: [other strategy slugs, or []]
     actors: [actor slugs involved, or []]
     funding-events: [funding-event slugs if known, or []]
     locations: [location slugs if known, or []]
     tags: [3-6 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

3. ACTOR — a person or organization with a named role in A2Zero.
   Create only when a clear role is described in this section. Do NOT create for passing mentions.
   Slug: "actors/{kebab-name}" (use acronym if that IS the canonical name)
   Frontmatter:
     type: actor
     title: (full name)
     actor-type: (person | government-office | nonprofit | utility | university | funder)
     role: (their role in A2Zero, one phrase)
     affiliation: (parent organization slug, or null)
     elected: (true | false | null — null if not a person)
     active-years: [list of years as integers mentioned in source, or []]
     programs-involved: [initiative or topic slugs mentioned in section, or []]
     tags: [3-5 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

4. FUNDING-EVENT — a specific dollar allocation with a named source AND recipient.
   Create only when both an amount AND a funding source are explicitly stated.
   Slug: "funding/{kebab-fund-name-year}"
   Frontmatter:
     type: funding-event
     title: (descriptive fund name including org and year)
     date: (YYYY or YYYY-MM)
     amount: (integer in dollars, e.g. 10000000)
     currency: USD
     fund-type: (federal-grant | state-grant | local-millage | philanthropic-grant | utility-program | federal-incentive | budget-allocation)
     source-org: (funder actor slug)
     recipient: (recipient actor slug)
     programs: [initiative slugs this funding supports, or []]
     status: (announced | awarded | disbursed | completed | terminated | on-hold)
     transferable: (true | false)
     tags: [3-5 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

5. TECHNOLOGY — a technology type Ann Arbor is deploying in A2Zero programs.
   Create only when barriers, costs, or deployment details are documented — not for passing mentions.
   Create when a technology has a dedicated initiative page or when its challenges are described.
   Slug: "technology/{kebab-tech-common-name}"
   Frontmatter:
     type: technology
     title: (full technology name)
     common-name: (short common name, e.g. "geothermal" | "solar" | "heat-pump")
     tech-type: (heating-cooling | solar | storage | efficiency | grid | ev | building-envelope | other)
     a2zero-context: (1-sentence description of how Ann Arbor is using this technology)
     initiatives: [initiative slugs using this technology, or []]
     locations: [location slugs where deployed, or []]
     deployment-status: (planned | in-progress | operational | completed | abandoned)
     cost-context: (string summarizing known costs, or null)
     barriers-encountered: [list of barrier keyword strings, or []]
     transferability: (high | medium | low)
     tags: [3-6 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

6. LOCATION — a specific place that is a named site of A2Zero program activity.
   Create when a location is named as a site of initiative activity, not just mentioned in passing.
   Slug: "locations/{kebab-location-name}"
   Frontmatter:
     type: location
     title: (full location name)
     location-type: (county | city | neighborhood | park | facility | infrastructure | district | school)
     parent-location: (parent location slug, e.g. "locations/bryant-neighborhood", or null)
     owned-by: (city | county | nonprofit | university | school-district | private | null)
     initiatives: [initiative slugs active at this location, or []]
     tags: [3-5 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

7. CONTRADICTION — conflicting claims about the same fact from the same or different sources.
   Create when numbers, dates, counts, or status claims conflict within or across sources.
   Do NOT silently resolve the conflict — create the page and document both sides.
   Slug: "contradictions/{kebab-brief-description}"
   Frontmatter:
     type: contradiction
     title: (brief description of the conflict)
     sources: [list of source UUIDs involved]
     cross-source: (true if conflict is between different source types; false if within same source)
     status: unresolved  # always "unresolved" at creation; human resolves
     tags: [3-5 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)
   Body: document both conflicting claims side by side, each with (source: uuid) citation.
   Include a best-guess explanation if one is plausible (e.g. different reporting scopes).

8. MEETING — a deliberative body meeting where A2Zero agenda items were discussed.
   Create when an agenda item, argument, or vote related to A2Zero is documented in the source.
   Slug: "meetings/YYYY-MM-DD-{body-slug}"  e.g. "meetings/2024-09-16-city-council"
   Frontmatter:
     type: meeting
     title: "{Body} — {YYYY-MM-DD} ({brief A2Zero topic})"
     date: (YYYY-MM-DD)
     body: (city-council | sustainability-commission | planning-commission | other)
     source-type: (council-transcript | press-release | annual-report | other)
     source-uuid: (source UUID)
     agenda-items: [initiative or commitment slugs discussed, or []]
     decisions: [list of decision strings, or []]
     actors: [actor slugs who participated, or []]
     tags: [3-5 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

9. FRAMING — how an A2Zero issue is deliberately talked about by stakeholders.
   Create only for named framing strategies with documented strategic intent — not every
   communications mention. The framing must be deliberate and have political/rhetorical significance.
   Slug: "framing/{kebab-framing-title}"
   Frontmatter:
     type: framing
     title: (descriptive framing title, e.g. "'Community Ownership' vs. 'Municipalization'")
     initiative: (initiative slug this framing applies to, or null)
     period: (YYYY-YYYY or YYYY)
     actors: [actor slugs who used this framing, or []]
     audiences: [public | city-council | utility-ratepayers | environmental-advocates | other]
     evolution: (true if framing shifted deliberately over time; false otherwise)
     tags: [3-5 keywords]
     source-first-seen: (source UUID)
     last-updated: (today's date YYYY-MM-DD)

10. POLITICAL-EVENT — a discrete political outcome with lasting legal or political effect.
    Create for council resolutions, referendums, elections, key appointments.
    Distinguish from MEETING: MEETING = where the debate happened; POLITICAL-EVENT = the legal outcome.
    For significant votes, create BOTH a meeting page AND a political-event page.
    Slug: "political-events/YYYY-MM-DD-{slug}"
    Frontmatter:
      type: political-event
      title: (descriptive title including body and outcome)
      date: (YYYY-MM-DD)
      event-type: (referendum | council-resolution | election | appointment | legal-ruling | regulatory-decision)
      outcome: (passed | failed | approved | rejected | appointed | other)
      margin: (vote margin string e.g. "8-3" or "62% yes", or null)
      legal-effect: (1-sentence description of what this authorizes or prohibits, or null)
      programs-authorized: [initiative or commitment slugs authorized, or []]
      actors: [actor slugs involved, or []]
      tags: [3-5 keywords]
      source-first-seen: (source UUID)
      last-updated: (today's date YYYY-MM-DD)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT SCHEMA
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Every element of the returned JSON array must have exactly these four keys:
{
  "page_type": "<one of the 10 types above>",
  "slug": "<category/kebab-name>",
  "frontmatter": { <required fields per type listed above> },
  "body": "<2-4 factual sentences. Every factual sentence ends with (source: SOURCE_UUID).>"
}
Return ONLY the JSON array. No prose, no markdown fence, no explanation."""


def parse_llm_pages_response(raw: str) -> list[dict]:
    cleaned = re.sub(r"^```(?:json)?\n?", "", raw.strip())
    cleaned = re.sub(r"\n?```$", "", cleaned)
    data = json.loads(cleaned)
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON array, got {type(data).__name__}")
    return data


def validate_page_spec(spec: dict) -> list[str]:
    errors = []
    for field in ("page_type", "slug", "frontmatter", "body"):
        if field not in spec:
            errors.append(f"missing required field: {field}")
    if "body" in spec and not spec.get("body"):
        errors.append("body must not be empty")
    if "page_type" in spec:
        pt = spec["page_type"]
        if pt not in VALID_PAGE_TYPES:
            errors.append(
                f"invalid page_type: {pt!r} — must be one of {sorted(VALID_PAGE_TYPES)}"
            )
        elif pt in PASS3_FORBIDDEN_TYPES:
            errors.append(
                f"page_type {pt!r} is forbidden in Pass 3 — "
                f"these pages are pre-created or generated by a separate process"
            )
    return errors


def write_or_append_page(spec: dict, wiki_root: str, source_uuid: str):
    slug = spec["slug"]
    page_path = Path(wiki_root) / (slug + ".md")

    if page_path.exists():
        existing_body = load_existing_body(str(page_path))
        new_section = f"\n<!-- source: {source_uuid} -->\n{spec['body']}\n"
        append_to_wiki_page(str(page_path), new_section, source_uuid)
        verify_existing_body_unchanged(str(page_path), existing_body)
    else:
        page = build_wiki_page(
            page_type=spec["page_type"],
            slug=slug,
            frontmatter=spec["frontmatter"],
            body=spec["body"],
        )
        write_wiki_page(page, wiki_root, exist_ok=False)


def extract_wiki_pages_from_chunk(
    chunk_text: str,
    source_uuid: str,
    context_header: str,
    source_type: str,
    wiki_root: str,
    run_date: str,
) -> list[dict]:
    try:
        client = anthropic.Anthropic()
        prompt = (
            f"{context_header}\n\n"
            f"[SECTION CONTENT]\n{chunk_text}\n[END SECTION]\n\n"
            f"Source UUID: {source_uuid}\n"
            f"Source type: {source_type}\n"
            f"Today's date: {run_date}"
        )
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=8192,
            temperature=0.2,
            system=WIKI_PAGES_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        if response.stop_reason == "max_tokens":
            print("[wiki_writer] WARNING: response truncated (max_tokens hit). Chunk skipped.")
            return []
        raw = response.content[0].text
        specs = parse_llm_pages_response(raw)
    except Exception as e:
        print(f"[wiki_writer] WARNING: page extraction failed for chunk: {e}")
        return []

    written = []
    for spec in specs:
        errors = validate_page_spec(spec)
        if errors:
            print(
                f"[wiki_writer] WARNING: invalid page spec skipped: {errors} "
                f"— {spec.get('slug', '?')}"
            )
            continue
        try:
            write_or_append_page(spec, wiki_root=wiki_root, source_uuid=source_uuid)
            written.append(spec)
        except Exception as e:
            print(f"[wiki_writer] WARNING: failed to write page {spec.get('slug', '?')}: {e}")

    return written
